apiVersion: v1
kind: Service
metadata:
  name: tat-dashboard
  namespace: dashboards
spec:
  selector:
    app: tat-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: NodePort
